name: Moped Build

#on:
#  push:
#    branches: [ master ]
#  pull_request:
#    branches: [ master ]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - use: mxcl/xcodebuild@v1

#- name: mxcl/Xcodebuild
#  uses: mxcl/xcodebuild@v1.7.0
