name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    name: Build with scheme
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: |
          rm -f Moped.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
          xcodebuild -scheme Moped -derivedDataPath ./build xcbuild
          mv xcbuild/Build/Products/Debug/Moped.app .
          zip -9 Moped.zip Moped.app
